---
title: "Comparing and contrasting heterogeneous single cell profiles using Analogizer"
author: "Joshua D. Welch"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Comparing and contrasting heterogeneous single cell profiles using Analogizer}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Data Preprocessing
The algorithm takes a list of two or more digital gene expression (DGE) matrices as input. Genes should be in rows and cells in columns.
Before running the factorization, we need to normalize the data to account for different numbers of UMIs per cell,
select variable genes, and scale the data. Note that we do not center the data because nonnegative matrix factorization accepts only
positive values. The selectGenes function performs variable gene selection on each of the datasets separately, then takes the union. Note that coresponding genes in each dataset need to have the same names (though the genes do not need to be in the same order in each dataset). For cross-species analysis, it may be convenient to convert all gene names to uppercase; you can do this using the capitalize=T option of the selectGenes function.
```r
dge1 = readRDS("dge1.RDS") #genes in rows, cells in columns, rownames and colnames included. Sparse matrix format is accepted.
dge2 = readRDS("dge2.RDS")
analogy = Analogizer(list(name1=dge1,name2=dge2)) #Can also pass in more than 2 datasets
analogy = normalize(analogy)
analogy = selectGenes(analogy,varthresh = 0.1)
analogy = scaleNotCenter(analogy)
```

## Performing the Factorization
Next we perform the factorization using an alternating least squares algorithm. After performing the factorization,
we identify cells that load on corresponding cell factors and quantile normalize their factor loadings across datasets.
The key parameters here are the number of factors (k), the penalty parameter (lambda), and the clustering resolution.
In most cases, the default settings of lambda=5.0 and resolution=1.0 provide reasonable results.
```r
analogy = optimizeALS(analogy,k=20) 
analogy = quantile_align_SNF(analogy) #SNF clustering and quantile alignment
```

## Visualizing the results
```r
analogy = run_tSNE(analogy)
plotByDatasetAndCluster(analogy) #Can also pass in different set of cluster labels to plot
pdf("word_clouds.pdf")
plot_word_clouds(analogy)
dev.off()
```

## Finding marker genes
We can use the factorization to identify shared and dataset-specific markers. The function below returns a list,
where the first element contains dataset-specific markers for dataset 1, the second element contains shared
markers, the third element contains dataset-specific markers for dataset 2, and the last 2 elements indicate 
the number of factors in which each marker is found. This information allows the identification
of ubiquitous vs. cell-type-specific dataset differences.
```r
markers = get_factor_markers(analogy,num_genes=10)
```


## Selecting k and lambda
The kSuggestion and lambdaSuggestion functions can aid in selecting k and lambda. We want to find the smallest
k for which the increase in entropy metric begins to level off (an "elbow" in the plot). Similarly, we want the
smallest lambda for which the alignment metric stabilizes.
```r
kSuggestion(analogy) # plot entropy metric to find an elbow that can be used to select the number of factors
lambdaSuggestion(analogy,k) # plot alignment metric to find an elbow that can be used to select the value of lambda
```

## Updating the Factorization
If we want to add new data, change k or lambda, or re-analyze a subset of the data, the functions
below provide an efficient method of updating. This is much faster than the naive approach of 
simply re-running the optimizeALS algorithm.
```r
analogy = optimizeNewK(analogy,k=15) #Can also decrease K
analogy = optimizeNewData(analogy,newdata=list(name1=dge1.new,name2=dge2.new),which.datasets=list(name1,name2),add.to.existing=T) #Add new batches from the same condition/technology/species/protocol
analogy = optimizeNewData(analogy,newdata=list(name3=dge3,name4=dge4),which.datasets=list(name1,name2),add.to.existing=F) #Add completely new datasets. Specify which existing datasets are most similar.
analogy = optimizeSubset(analogy,cell.subset) #cell.subset is a list of cells to retain from each dataset
```
