---
title: "Install LIGER with R"
author: "Yichen Wang"
date: "2023-11-05"
output: 
  html_document:
    toc: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

Before setting up the "rliger" package, users should have [R](https://www.r-project.org/) version 3.6.0 or higher. 
  
## LIGER is available on CRAN

To install the latest stable release, please run the following command in R console:

```{R}
install.packages("rliger")
```

## Building from source

The developmental versions as well as source version of the previous versions are accessible from GitHub. We are currently contributing to the repository `welch-lab/liger` in branch `newObj` for the latest developmental version. To install the latest version from GitHub, please run the following command in R console:

```{R}
if (!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("welch-lab/liger@newObj")
```

If you encounter issues when building from source, please see below sections for details about some dependencies.

**Please note that the latest version (>=1.9.9) is massively updated compared to prior versions, and functions are not directly compatible with the old version objects which users might possess. Please use `readLiger()` to load old RDS files or `convertOldLiger()` to convert a loaded object into the up-to-date structure. You might need to be careful when overwriting existing analysis because we don't provide methods to convert new the structure backwards.**

### Compiler setup

Windows users will need to install [Rtools](https://cran.r-project.org/bin/windows/Rtools/) which can be downloaded from CRAN. After downloading it, open the file and follow the prompt to install.

MacOS users will need Clang and gfortran, which can also be found on [CRAN Mac Tools](https://mac.r-project.org/tools/).

### Installing HDF5 Library

HDF5 library is required for interacting with H5 files. It can be installed via the following commands.

| System                                    | Command
|:------------------------------------------|:---------------------------------|
|OS X (using Homebrew or Conda)         | `brew install hdf5` or `conda install -c anaconda hdf5`
|Debian-based systems (including Ubuntu) | `sudo apt-get install libhdf5-dev`
|Systems supporting yum and RPMs        | `sudo yum install hdf5-devel`
|Windows | Go to [HDF5 website](https://www.hdfgroup.org/downloads/hdf5/) and download the proper installer

### Installing RcppPlanc

[RcppPlanc](https://github.com/welch-lab/RcppPlanc) is an extension R package built basing on [Planc](https://github.com/ramkikannan/planc). We implemented highly optimized iNMF algorithm and its variants here for the new version upgrade. It is currently only available via GitHub.

```{R}
devtools::install_github("welch-lab/RcppPlanc")
```

Please refer to [RcppPlanc GitHub repository](https://github.com/welch-lab/RcppPlanc) for detail and more support.

### Installing FIt-SNE

For dimensionality reduction, we have options of UMAP and t-SNE. For UMAP, we depend on *uwot* which is readily scalable with large datasets. For t-SNE, we by default use *Rtsne*, which is not scalable for large datasets. We allow using another implementation of t-SNE, namingly FIt-SNE, for efficient computation. FIt-SNE is not distributed with the package or CRAN, thus users need to install it following steps below.

#### 1. Create a directory fo organizing the source code

```{bash}
cd path/you/need
mkdir FItSNE_local
```

#### 1. Install FFTW library.

Download FFTW from [here](http://www.fftw.org/). For UNIX like users, run the following command in terminal. The following commands in terminal show how to locally install the library of version 3.3.10 as this tutorial is written down. You can check their official website out if an update is available. You can simply replace the version number in the URL and the file name to update the installation.

```{bash}
cd FItSNE_local
curl ftp://ftp.fftw.org/pub/fftw/fftw-3.3.10.tar.gz -o fftw-3.3.10.tar.gz
tar -xvzf  fftw-3.3.10.tar.gz
cd fftw-3.3.10
./configure --prefix=`pwd`
make
make install prefix=`pwd`
```

Here the FFTW library is installed in the directory where the source code is located. You can change the part ``pwd`` to any other path (no quotes needed) or even remove the `--prefix` token to globally install the library if you do have the root access. A folder `lib` with files named by `libfftw3*` must be presented at current location.

#### 2. Install FIt-SNE

We next download FIt-SNE from GitHub and compile the part we need for the R wrapper functionality.

```{bash}
cd ../ # back to FItSNE_local
git clone https://github.com/KlugerLab/FIt-SNE.git
cd FIt-SNE
g++ -std=c++11 -O3  src/sptree.cpp src/tsne.cpp src/nbodyfft.cpp -o bin/fast_tsne -pthread -L../fftw-3.3.10/lib -lfftw3 -lm
pwd
```

A folder `bin` with a file named `fast_tsne` must be presented at current location. The command `pwd` shows the location to the binary and you will need the printed path for the next step.

#### 3. Run t-SNE with Flt-SNE

Now, we've had the binary compiled, and command `pwd` shows the location to the binary. Then back to an R LIGER analysis, the following command can be used to invoke the binary. Just simply pass a string containing what `pwd` shows to the argument `fitsnePath` in `runTSNE()` function and switch `method = "fftRtsne"`.

```{R}
ligerObj <- runTSNE(ligerObj, method = "fftRtsne", fitsnePath = "path/you/need/FItSNE_local/FIt-SNE")
```
