# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunModularityClusteringCpp <- function(SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename) {
    .Call(`_rliger2_RunModularityClusteringCpp`, SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename)
}

colNormalize_dense_cpp <- function(x, L) {
    .Call(`_rliger2_colNormalize_dense_cpp`, x, L)
}

select_factor_cpp <- function(all_data, knn, threshold) {
    .Call(`_rliger2_select_factor_cpp`, all_data, knn, threshold)
}

colAggregateMedian_dense_cpp <- function(x, group, n) {
    .Call(`_rliger2_colAggregateMedian_dense_cpp`, x, group, n)
}

scaleNotCenter_byRow_rcpp <- function(x) {
    .Call(`_rliger2_scaleNotCenter_byRow_rcpp`, x)
}

scaleNotCenter_byRow_perDataset_rcpp <- function(x, ann, n) {
    .Call(`_rliger2_scaleNotCenter_byRow_perDataset_rcpp`, x, ann, n)
}

rowVars_sparse_rcpp <- function(x, means) {
    .Call(`_rliger2_rowVars_sparse_rcpp`, x, means)
}

rowDivide_rcpp <- function(x, v) {
    .Call(`_rliger2_rowDivide_rcpp`, x, v)
}

sumSquaredDeviations <- function(x, means) {
    .Call(`_rliger2_sumSquaredDeviations`, x, means)
}

denseZScore <- function(x, m) {
    .Call(`_rliger2_denseZScore`, x, m)
}

rowVarsDense <- function(x, m) {
    .Call(`_rliger2_rowVarsDense`, x, m)
}

SparseRowVarStd <- function(x, mu, sd, vmax) {
    .Call(`_rliger2_SparseRowVarStd`, x, mu, sd, vmax)
}

colAggregateSums_sparse <- function(x, group, ngroups) {
    .Call(`_rliger2_colAggregateSums_sparse`, x, group, ngroups)
}

sample_cpp <- function(x, size) {
    .Call(`_rliger2_sample_cpp`, x, size)
}

#' Fast calculation of feature count matrix
#'
#' @param bedmat A feature count list generated by bedmap
#' @param barcodes A list of barcodes
#'
#' @return A feature count matrix with features as rows and barcodes as
#' columns
#' @export
#' @examples
#' \dontrun{
#' gene.counts <- makeFeatureMatrix(genes.bc, barcodes)
#' promoter.counts <- makeFeatureMatrix(promoters.bc, barcodes)
#' samnple <- gene.counts + promoter.counts
#' }
makeFeatureMatrix <- function(bedmat, barcodes) {
    .Call(`_rliger2_makeFeatureMatrix`, bedmat, barcodes)
}

cluster_vote_rcpp <- function(nn_ranked, clusts) {
    .Call(`_rliger2_cluster_vote_rcpp`, nn_ranked, clusts)
}

max_factor_rcpp <- function(H, dims_use, center = FALSE) {
    .Call(`_rliger2_max_factor_rcpp`, H, dims_use, center)
}

ComputeSNN <- function(nn_ranked, prune) {
    .Call(`_rliger2_ComputeSNN`, nn_ranked, prune)
}

WriteEdgeFile <- function(snn, filename, display_progress) {
    invisible(.Call(`_rliger2_WriteEdgeFile`, snn, filename, display_progress))
}

DirectSNNToFile <- function(nn_ranked, prune, display_progress, filename) {
    .Call(`_rliger2_DirectSNNToFile`, nn_ranked, prune, display_progress, filename)
}

cpp_rank_matrix_dgc <- function(x, p, nrow, ncol) {
    .Call(`_rliger2_cpp_rank_matrix_dgc`, x, p, nrow, ncol)
}

rowAggregateSum_sparse <- function(X, groups, ngroups) {
    .Call(`_rliger2_rowAggregateSum_sparse`, X, groups, ngroups)
}

colAggregateSum_sparse <- function(X, groups, ngroups) {
    .Call(`_rliger2_colAggregateSum_sparse`, X, groups, ngroups)
}

colNNZAggr_sparse <- function(X, groups, ngroups) {
    .Call(`_rliger2_colNNZAggr_sparse`, X, groups, ngroups)
}

rowNNZAggr_sparse <- function(X, groups, ngroups) {
    .Call(`_rliger2_rowNNZAggr_sparse`, X, groups, ngroups)
}

